baseURL = 'https://mosquid.github.io/'
languageCode = 'en-us'
title = 'Mosquid'
theme = 'salinger'
copyright = 'Mosquid'
author = "Dmitry Mosquid"
header = "<strong>Hi, I'm John. 👋 </strong>"
keywords = [ "Portfolio", "developer", "coding", "maker"]
showHeaderOnHomepage = false


[params]
  Header = 'Dmitry Mosquid'
  


[[params.social]]
  name = "github"
  url = "https://github.com/mosquid"
  icon = "fa fa-github"
  before = "Reach me on "

[[params.social]]
  name = "telegram"
  icon = "fa fa-telegram"
  url = "https://t.me/fnbme"
  before = "and on "
  after = "."


[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true